//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public int GroupId { get; set; }
        public string UserId { get; set; }
        public int Role { get; set; }
        public string AccessToken { get; set; }
        public Nullable<System.DateTime> AccessExpiration { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual MFUser MFUser { get; set; }
    }
}
