//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceDay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewEventUserAttendance
    {
        public int EventId { get; set; }
        public int GroupId { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public string Url { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string CreatorId { get; set; }
        public string UserId { get; set; }
        public int Attending { get; set; }
        public Nullable<int> AttendanceCount { get; set; }
    }
}
